// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Infrastructure.Data;

#nullable disable

namespace SchoolManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260513214837_AddReminderEmailSentToStudentExam")]
    partial class AddReminderEmailSentToStudentExam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.Core.Entities.Academician", b =>
                {
                    b.Property<string>("AcademicianId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("academician_id");

                    b.Property<string>("AcademicianEmail")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("academician_email");

                    b.Property<string>("AcademicianPhone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("academician_phone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.HasKey("AcademicianId");

                    b.HasIndex("AcademicianEmail")
                        .IsUnique();

                    b.ToTable("ACADEMICIAN");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Advisor", b =>
                {
                    b.Property<string>("AdvisorId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("advisor_id");

                    b.Property<string>("AdvisorMail")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("advisor_mail");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name_surname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.HasKey("AdvisorId");

                    b.HasIndex("AdvisorMail")
                        .IsUnique();

                    b.ToTable("ADVISOR");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Exam", b =>
                {
                    b.Property<string>("ExamId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("exam_id");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("exam_date");

                    b.Property<string>("ExamDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("exam_description");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("exam_type");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subject_id");

                    b.HasKey("ExamId");

                    b.HasIndex("SubjectId");

                    b.ToTable("EXAM");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Excuse", b =>
                {
                    b.Property<string>("ExcuseId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("excuse_id");

                    b.Property<string>("AdvisorId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("advisor_id");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("longtext")
                        .HasColumnName("document_path");

                    b.Property<string>("ExamId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("exam_id");

                    b.Property<string>("ExcuseDescription")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("excuse_description");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("request_date");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("response_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("StudentNo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("student_no");

                    b.HasKey("ExcuseId");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentNo");

                    b.ToTable("EXCUSE");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Student", b =>
                {
                    b.Property<string>("StudentNo")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("student_no");

                    b.Property<int>("ActiveBarCount")
                        .HasColumnType("int")
                        .HasColumnName("active_bar_count");

                    b.Property<string>("AdvisorId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("advisor_id");

                    b.Property<decimal>("GPA")
                        .HasColumnType("DECIMAL(3,2)")
                        .HasColumnName("GPA");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("grade");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_locked");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("locked_at");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name_surname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("StudentMail")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("student_mail");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("unlocked_at");

                    b.HasKey("StudentNo");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("StudentMail")
                        .IsUnique();

                    b.ToTable("STUDENT");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.StudentExam", b =>
                {
                    b.Property<int>("StudentNoExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_no_exam_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StudentNoExamId"));

                    b.Property<string>("ExamId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("exam_id");

                    b.Property<string>("ParticipationNotification")
                        .HasColumnType("longtext")
                        .HasColumnName("participation_notification");

                    b.Property<string>("ParticipationStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("participation_status");

                    b.Property<bool>("ReminderEmailSent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("reminder_email_sent");

                    b.Property<string>("StudentNo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("student_no");

                    b.HasKey("StudentNoExamId");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentNo");

                    b.ToTable("STUDENT_EXAM");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.StudentSubject", b =>
                {
                    b.Property<string>("StudentNoSubjectId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("student_no_subject_id");

                    b.Property<string>("StudentNo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("student_no");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subject_id");

                    b.HasKey("StudentNoSubjectId");

                    b.HasIndex("StudentNo");

                    b.HasIndex("SubjectId");

                    b.ToTable("STUDENT_SUBJECT");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subject_id");

                    b.Property<string>("AcademicianId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("academician_id");

                    b.Property<int>("DayIndex")
                        .HasColumnType("int")
                        .HasColumnName("day_index");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("subject_name");

                    b.HasKey("SubjectId");

                    b.HasIndex("AcademicianId");

                    b.ToTable("SUBJECT");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Exam", b =>
                {
                    b.HasOne("SchoolManagement.Core.Entities.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Excuse", b =>
                {
                    b.HasOne("SchoolManagement.Core.Entities.Advisor", "Advisor")
                        .WithMany()
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolManagement.Core.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId");

                    b.HasOne("SchoolManagement.Core.Entities.Student", "Student")
                        .WithMany("Excuses")
                        .HasForeignKey("StudentNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advisor");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Student", b =>
                {
                    b.HasOne("SchoolManagement.Core.Entities.Advisor", "Advisor")
                        .WithMany("Students")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Advisor");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.StudentExam", b =>
                {
                    b.HasOne("SchoolManagement.Core.Entities.Exam", "Exam")
                        .WithMany("StudentExams")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Core.Entities.Student", "Student")
                        .WithMany("StudentExams")
                        .HasForeignKey("StudentNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.StudentSubject", b =>
                {
                    b.HasOne("SchoolManagement.Core.Entities.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudentNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Core.Entities.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Subject", b =>
                {
                    b.HasOne("SchoolManagement.Core.Entities.Academician", "Academician")
                        .WithMany("Subjects")
                        .HasForeignKey("AcademicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Academician");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Academician", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Advisor", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Exam", b =>
                {
                    b.Navigation("StudentExams");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Student", b =>
                {
                    b.Navigation("Excuses");

                    b.Navigation("StudentExams");

                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("SchoolManagement.Core.Entities.Subject", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("StudentSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
